### ISSUE TITLE
'PosixPath' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by aroly** [synacktiv/eos#7]
Hello,

I just installed the tool and tried it, I have a (Python?) error: 

```
eos scan https://www.foo.com/fr 
[+] Starting scan on https://www.foo.com/fr
[+] 2021-08-02 10:00:20.542212 is a great day
[x] 'PosixPath' object has no attribute 'startswith'
[x] Aborted
```

I searched online, it seems to be related to a wrong Python version, which is weird since I used python3.8 to install eos. 

EOS version is 1.1 and seems correctly installed:

```
eos -h
usage: eos [-h] [-V] [-v] [--no-colors] {scan,sources,get,creds,cookies} ...

  ███████╗ ██████╗ ███████╗
  ██╔════╝██╔═══██╗██╔════╝
  █████╗  ██║   ██║███████╗
  ██╔══╝  ██║   ██║╚════██║
  ███████╗╚██████╔╝███████║  Enemies Of Symfony
  ╚══════╝ ╚═════╝ ╚══════╝  v1.1

positional arguments:
  {scan,sources,get,creds,cookies}
    scan                 perform a full scan
    sources              download application source code
    get                  download a file from the application
    creds                extract credentials from request logs
    cookies              craft remember me cookies with a great lifetime

optional arguments:
  -h, --help             show this help message and exit
  -V, --version          display version info
  -v, --verbose          increase verbosity
  --no-colors            disable colors in output

examples:
  eos scan http://localhost
  eos scan -H 'Cookie: foo=bar; john=doe' -H 'User-Agent: EOS' http://localhost
  eos get http://localhost config/services.yaml
  eos cookies -u jane_admin -H '$2y$13$IMalnQpo7xfZD5FJGbEadOcqyj2mi/NQbQiI8v2wBXfjZ4nwshJlG' -s 67d829bf61dc5f87a73fd814e2c9f629
```

Any idea what could cause this issue ?

**Comment by qde-a** [comment]
same here

**Comment by aroly** [comment]
Workaround: it works with python3.7 but not python3.8, maybe you should adapt the README accordingly.

Cheers,

A.

**Comment by aevy-syn** [comment]
Hi, sorry for the late response.
The tool has been developed using Python3.8. I can't reproduce your issue, would you mind sharing more details please ?
Thanks

**Comment by savushkin-yauheni** [comment]
The same issue on Python 3.8.10

**Comment by aevy-syn** [comment]
Thank you, the issue seems to only occur on Python < 3.8.11. It has now been fixed.
